package upgrade

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestCompareVersions(t *testing.T) {
	cases := []struct {
		a, b string
		want int
		ok   bool
	}{
		{"0.0.7", "0.0.8", -1, true},
		{"0.0.8", "0.0.7", 1, true},
		{"0.0.7", "0.0.7", 0, true},
		{"v0.1.0", "0.0.9", 1, true},
		{"0.1", "0.1.0", 0, true},
		{"1.0.0", "0.99.99", 1, true},
		{"0.0.10", "0.0.9", 1, true},
		{"Snapshot-2026-09-17", "0.0.7", 0, false},
		{"", "0.0.7", 0, false},
	}
	for _, c := range cases {
		got, ok := CompareVersions(c.a, c.b)
		if ok != c.ok || (ok && got != c.want) {
			t.Errorf("CompareVersions(%q,%q) = (%d,%v)，期望 (%d,%v)", c.a, c.b, got, ok, c.want, c.ok)
		}
	}
}

func TestServerAssetName(t *testing.T) {
	if n, ok := ServerAssetName("linux", "amd64"); !ok || n != "komari-linux-amd64" {
		t.Errorf("linux/amd64 = (%q,%v)", n, ok)
	}
	if n, ok := ServerAssetName("linux", "arm64"); !ok || n != "komari-linux-arm64" {
		t.Errorf("linux/arm64 = (%q,%v)", n, ok)
	}
	// 发布流程只产出两个 linux 资产：其它平台必须明确"不支持"，而不是猜一个下载地址。
	for _, c := range [][2]string{{"darwin", "amd64"}, {"windows", "amd64"}, {"linux", "386"}, {"linux", "riscv64"}} {
		if _, ok := ServerAssetName(c[0], c[1]); ok {
			t.Errorf("%s/%s 不应有资产", c[0], c[1])
		}
	}
}

func TestParseChecksums(t *testing.T) {
	data := []byte(`# generated by scripts/build-komari.sh
aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666aaaa7777bbbb8888  komari-linux-amd64
AAAA1111BBBB2222CCCC3333DDDD4444EEEE5555FFFF6666AAAA7777BBBB8888 *komari-linux-arm64

garbage-line-without-hash
deadbeef  too-short-hash
`)
	sums := ParseChecksums(data)
	if len(sums) != 2 {
		t.Fatalf("解析出 %d 条，期望 2 条：%v", len(sums), sums)
	}
	if got := sums["komari-linux-amd64"]; got != "aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666aaaa7777bbbb8888" {
		t.Errorf("amd64 校验和错误：%s", got)
	}
	// 十六进制大小写归一化：便于和 sha256sum 输出直接比较
	if got := sums["komari-linux-arm64"]; got != "aaaa1111bbbb2222cccc3333dddd4444eeee5555ffff6666aaaa7777bbbb8888" {
		t.Errorf("arm64 校验和未归一化为小写：%s", got)
	}
}

func releaseJSON(tags ...string) []githubRelease {
	out := make([]githubRelease, 0, len(tags))
	for _, tag := range tags {
		out = append(out, githubRelease{
			TagName: tag,
			Assets: []githubAsset{
				{Name: "komari-linux-amd64", BrowserDownloadURL: "https://example.invalid/" + tag + "/amd64"},
				{Name: ChecksumAssetName, BrowserDownloadURL: "https://example.invalid/" + tag + "/sums"},
			},
		})
	}
	return out
}

func newFakeAPI(t *testing.T, releases []githubRelease) (*Client, *httptest.Server) {
	t.Helper()
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Header.Get("User-Agent") == "" {
			t.Errorf("请求缺少 User-Agent：%s", r.URL.Path)
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(releases)
	}))
	t.Cleanup(srv.Close)
	return &Client{Repo: "owner/repo", APIBase: srv.URL, HTTP: srv.Client()}, srv
}

func TestLatestStableAndFindRelease(t *testing.T) {
	ctx := context.Background()
	c, _ := newFakeAPI(t, releaseJSON("0.0.9", "0.0.11", "0.0.10"))

	latest, newer, err := c.LatestStable(ctx, "0.0.7")
	if err != nil {
		t.Fatalf("LatestStable: %v", err)
	}
	if !newer || latest.Tag != "0.0.11" {
		t.Fatalf("期望最新 0.0.11 且比 0.0.7 新，实际 %+v newer=%v", latest, newer)
	}

	// 已经是最新：newer=false，但不应报错
	if _, newer, err := c.LatestStable(ctx, "0.0.11"); err != nil || newer {
		t.Fatalf("已经最新时应 newer=false 且无错误，实际 newer=%v err=%v", newer, err)
	}

	r, err := c.FindRelease(ctx, "0.0.9")
	if err != nil || r.Tag != "0.0.9" {
		t.Fatalf("FindRelease: %+v %v", r, err)
	}
	if _, err := c.FindRelease(ctx, "0.0.1"); err == nil {
		t.Fatal("不存在的 tag 应该报错")
	}
}

func TestStableReleasesSkipPrereleaseAndDraft(t *testing.T) {
	ctx := context.Background()
	releases := releaseJSON("0.0.10")
	releases = append(releases, githubRelease{TagName: "0.0.11-rc1", Prerelease: true})
	releases = append(releases, githubRelease{TagName: "0.0.12", Draft: true})
	c, _ := newFakeAPI(t, releases)

	list, err := c.StableReleases(ctx)
	if err != nil {
		t.Fatalf("StableReleases: %v", err)
	}
	if len(list) != 1 || list[0].Tag != "0.0.10" {
		t.Fatalf("应只保留稳定版 0.0.10，实际 %+v", list)
	}
}
